stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "we-dev-next"
  DOCKER_ORIGIN_PORT: "3000"
  DOCKER_RMOTE_PORT: "16090"

build:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - docker stop $DOCKER_IMAGE_NAME || true
    - docker rm $DOCKER_IMAGE_NAME || true
    - docker rmi $DOCKER_IMAGE_NAME || true
    - docker build -t $DOCKER_IMAGE_NAME .
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker run --name $DOCKER_IMAGE_NAME -p $DOCKER_RMOTE_PORT:$DOCKER_ORIGIN_PORT -d $DOCKER_IMAGE_NAME
  only:
    - main
  environment:
    name: production
